---
ansible_connection: local
ansible_become: yes
ansible_become_method: enable
ansible_user: student1
ansible_password: 'I_vMbzWf4bBYC.unQx5.'
ansible_become_pass: 'I_vMbzWf4bBYC.unQx5.'
ansible_network_os: eos


#Provider settings
creds_core_ssh:
  host: "{{ ansible_host }}"
  username: "{{ ansible_user }}"
  password: "{{ ansible_password }}"
  transport: cli
  timeout: 60

creds_core_eapi:
  host: "{{ ansible_host }}"
  username: "{{ ansible_user }}"
  password: "{{ ansible_password }}"
  transport: eapi
  use_ssl: False
  validate_certs: no
  timeout: 60

creds_napalm:
  hostname: "{{ ansible_host }}"
  username: "{{ ansible_user }}"
  password: "{{ ansible_password }}"
  dev_os: "eos"
  optional_args: {}



