---
- name: Set SNMP config
  hosts: [amsterdam-leaf1]
  gather_facts: no
  tasks:
    - name: Set SNMP config lines for host 192.168.99.254
      ios_config:
        lines:
          - snmp-server community Ansible-class RO
          - snmp-server trap-source Loopback0
          - snmp-server host 192.168.99.254 Ansible-class
      become: true
