---
- name: Set SNMP config
  hosts: [amsterdam-leaf1]
  gather_facts: no
  tasks:
    - name: 'Set SNMP config lines for host {{ snmp_host_ip }} RO'
      ios_config:
        lines:
          - 'snmp-server community {{ snmp_community }}'
          - snmp-server trap-source Loopback0

    - name: 'Set SNMP config lines for host {{ item }}'
      ios_config:
        lines:
          - 'snmp-server host {{ item }} {{ snmp_community }}'
      loop: '{{ snmp_host_ips }}'
