---
- name: Set Loopback1099
  hosts: amsterdam-spine1
  gather_facts: no
  tasks:
    - name: Set Loopback 1099 IP address
      ios_config:
        lines:
          - ip address 192.168.14.99 255.255.255.255
        parents: Interface Loopback1099

