---
provider_napalm:
  hostname: "{{ ansible_host }}"
  username: "{{ ansible_user }}"
  password: "{{ ansible_password }}"
  dev_os: "ios"
  optional_args:
    secret: "{{ ansible_password }}"
#    inline_transfer: True

