---
loopback_ip: 10.199.1.32
ospf:
  processid: 100
  ospf_area_default: 200
  global:
    - default auto-cost reference-bandwidth 100000
    - passive-interface default
  amsterdam-r1:
    - redistribute static subnets
    - redistribute bgp 1 subnets

ospf_intf_list:
  amsterdam-spine2: [GigabitEthernet0/0, GigabitEthernet0/1, GigabitEthernet0/2, GigabitEthernet0/3, GigabitEthernet0/5]

