# set_interface_ip.yaml

- name: Set interface IP with different modules
  hosts: amsterdam-spine1
  vars:
    - uplink_spine1_to_r1_intf: GigabitEthernet0/0
    - uplink_spine1_to_r1_ip: 172.20.30.12
    - uplink_spine1_to_r1_subnet: 255.255.255.254
    - uplink_spine1_to_r1_ip_cidr: 172.20.30.12/31
  tasks:
    - name: Set interface config - ios_config - exact match
      ios_config:
        lines:
          - description Naar amsterdam_r1 - Gi0/0 - 172.20.30.11/31
          - 'ip address {{ uplink_spine1_to_r1_ip }} {{ uplink_spine1_to_r1_subnet }}'
          - duplex auto
          - speed auto
          - media-type rj45
          - no cdp enable
        parents: 'interface {{ uplink_spine1_to_r1_intf }}'
        match: exact

    - name: Set interface config - cli_command - line by line in commands
      cli_command:
        command: '{{ item }}'
      loop:
        - config terminal
        - 'interface {{ uplink_spine1_to_r1_intf }}' 
        - 'ip address {{ uplink_spine1_to_r1_ip }} {{ uplink_spine1_to_r1_subnet }}'
        - duplex auto
        - speed auto
        - media-type rj45
        - no cdp enable
        - exit
    - name: Set interface config - net_l3_interface
      net_l3_interface:
        name: '{{ uplink_spine1_to_r1_intf }}'
        ipv4: '{{ uplink_spine1_to_r1_ip_cidr }}'      
