- name: NTP check
  hosts: amsterdam-leafs
  become: true
  vars:
    ntp_servers:
      - "ntp server 172.16.9.8"
      - "ntp server 172.16.9.16"
    extra_ntp_servers_no: []
  tasks:
    - name: Configure NTP Servers
      ios_config:
        lines: "{{ ntp_servers }}"

    - name: Obtain current NTP Servers
      ios_command:
        commands: "show run | inc ntp"
      register: output

    - set_fact:
        current_ntp: "{{ output.stdout_lines[0] }}"

    - name: Find extra NTP servers that should not be configured
      set_fact:
        extra_ntp_servers: "{{ current_ntp | difference(ntp_servers) | list }}"

    - name: "Construct the 'no ntp...' command to remove unneeded servers"
      set_fact:
        no_ntp_servers: "{{ lookup('template', './no_ntp_servers.j2') | from_yaml }}"

    - name: Remove unneeded NTP servers
      ios_config:
        lines: "{{ no_ntp_servers }}"
      when: no_ntp_servers

    - name: Obtain new NTP Servers
      ios_command:
        commands: "show run | inc ntp"
      register: output

    - name: current NTP config
      debug:
        msg: '{{ output.stdout_lines }}'
